### ISSUE TITLE
 [Previous line repeated 997 more times]  RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by littlestudent886** [MIRACLE-Center/YOLO_Universal_Anatomical_Landmark_Detection#15]
您好，谢谢您的代码。我在测试best.pt文件时遇见了递归错误，请问您该如何解决。具体报错如下
$ python3 main.py -d ../runs -r GU2Net -p test -C config.yaml -m gln -l u2net -n cephalometric -c best.pt
Traceback (most recent call last):
  File "/home/jgzn/PycharmProjects/YOLO/YOLO_Universal_Anatomical_Landmark_Detection-main/universal_landmark_detection/model/utils/yamlConfig.py", line 105, in update_config
    update_config(val, args)
  File "/home/jgzn/PycharmProjects/YOLO/YOLO_Universal_Anatomical_Landmark_Detection-main/universal_landmark_detection/model/utils/yamlConfig.py", line 105, in update_config
    update_config(val, args)
  File "/home/jgzn/PycharmProjects/YOLO/YOLO_Universal_Anatomical_Landmark_Detection-main/universal_landmark_detection/model/utils/yamlConfig.py", line 105, in update_config
    update_config(val, args)
  [Previous line repeated 997 more times]
RecursionError: maximum recursion depth exceeded

**Comment by littlestudent886** [comment]
您好，请问现在代码修改好了吗

**Comment by heqin-zhu** [comment]
还没，上面的方法可以解决
